In [113]:
import warnings as warn
warn.filterwarnings('ignore')

In [114]:
import numpy as np

In [115]:
l = [1,2,3,4,5]

In [116]:
arr = np.array(l)

In [117]:
arr = np.array(range(1,6))

In [118]:
type(arr)

numpy.ndarray

In [119]:
type(arr)

numpy.ndarray

In [120]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [121]:
np.array(l)

array([1, 2, 3, 4, 5])

In [122]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [123]:
np.asarray(l) == np.array(l)

array([ True,  True,  True,  True,  True])

In [124]:
arr1 = np.array([[1,2,3] , [2,3,4]])

In [125]:
arr1 = np.array([[1,2,3,4], [5,6,7,8]])

In [126]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [127]:
arr.ndim

1

In [128]:

arr1.ndim

2

In [129]:
arr.ndim

1

In [130]:
arr1.ndim

2

In [131]:
arr

array([1, 2, 3, 4, 5])

In [132]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [133]:
mat = np.matrix(l)

In [134]:
mat

matrix([[1, 2, 3, 4, 5]])

In [135]:
mat = np.matrix(l)

In [136]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [137]:
np.array(l)

array([1, 2, 3, 4, 5])

In [138]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [139]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [140]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

In [141]:
mat

matrix([[1, 2, 3, 4, 5]])

In [142]:
np.array(mat)

array([[1, 2, 3, 4, 5]])

In [46]:
np.asarray(mat)

array([[1, 2, 3, 4, 5]])

In [47]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

In [71]:
arr

array([1, 2, 3, 4, 5])

In [51]:
a = arr

In [52]:
a

array([100,   2,   3,   4,   5])

In [53]:
arr

array([100,   2,   3,   4,   5])

In [54]:
arr[0] = 100

In [55]:
arr

array([100,   2,   3,   4,   5])

In [56]:
a

array([100,   2,   3,   4,   5])

In [57]:
arr[1] = 143

In [58]:
arr

array([100, 143,   3,   4,   5])

In [59]:
a

array([100, 143,   3,   4,   5])

In [60]:
a[2] = 123

In [61]:
a

array([100, 143, 123,   4,   5])

In [62]:
arr

array([100, 143, 123,   4,   5])

In [63]:
b = np.copy(arr)

In [64]:
b = np.copy(arr)

In [65]:
b

array([100, 143, 123,   4,   5])

In [66]:
b[0] = 234

In [67]:
b

array([234, 143, 123,   4,   5])

In [68]:
arr[3] = 145

In [69]:
a

array([100, 143, 123, 145,   5])

In [70]:
 b

array([234, 143, 123,   4,   5])

In [71]:
b[4]= 120

In [72]:
arr

array([100, 143, 123, 145,   5])

In [73]:
np.fromfunction(lambda i,j: i**j, (5,5))

array([[  1.,   0.,   0.,   0.,   0.],
       [  1.,   1.,   1.,   1.,   1.],
       [  1.,   2.,   4.,   8.,  16.],
       [  1.,   3.,   9.,  27.,  81.],
       [  1.,   4.,  16.,  64., 256.]])

In [74]:
np.fromfunction(lambda i,j : i==j , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [75]:
0 ** 0

1

In [76]:
np.fromfunction(lambda i,j: i+j , (4,4))

array([[0., 1., 2., 3.],
       [1., 2., 3., 4.],
       [2., 3., 4., 5.],
       [3., 4., 5., 6.]])

In [77]:
np.fromfunction(lambda i,j : i*j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [78]:
[i*i for i in range(5)]

[0, 1, 4, 9, 16]

In [79]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [80]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [81]:
iter = (i*i for i in range(5))

In [82]:
iterable  = (i*i for i in range(5))

In [83]:
np.fromiter(iter, int)

array([ 0,  1,  4,  9, 16])

In [84]:
np.fromiter(iter, float)

array([], dtype=float64)

In [85]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [86]:
np.fromstring('23 45 56',sep  = ' ' )

array([23., 45., 56.])

In [87]:
np.fromstring('23,45,56',sep  = ',' )

array([23., 45., 56.])

In [88]:
np.fromstring('1 2 3', sep = ' ')

array([1., 2., 3.])

In [89]:
np.fromstring('1#2#3', sep = '#')

array([1., 2., 3.])

In [90]:
np.fromstring('1,2,3', sep = ',')

array([1., 2., 3.])

In [91]:
arr

array([100, 143, 123, 145,   5])

In [92]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [93]:
arr

array([100, 143, 123, 145,   5])

In [94]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [95]:
arr.ndim

1

In [96]:
arr1.ndim

2

In [97]:
arr.ndim

1

In [98]:
arr1.ndim

2

In [99]:
arr.size

5

In [100]:
arr1.size

8

In [101]:
arr.shape

(5,)

In [102]:
arr1.shape

(2, 4)

In [103]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [104]:
arr.dtype

dtype('int64')

In [105]:
arr1.dtype

dtype('int64')

In [106]:
arr

array([100, 143, 123, 145,   5])

In [107]:
arr.size

5

In [108]:
arr1.size

8

In [109]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [110]:
arr1.size

8

In [111]:
arr.dtype

dtype('int64')

In [112]:
arr1.dtype

dtype('int64')

In [144]:
np.array(range(1,6))

array([1, 2, 3, 4, 5])

In [145]:
np.asarray(range(1,6))

array([1, 2, 3, 4, 5])

In [146]:
np.asanyarray(range(1,6))

array([1, 2, 3, 4, 5])

In [148]:
np.array(np.matrix(range(1,6)))

array([[1, 2, 3, 4, 5]])

In [149]:
np.asarray(np.matrix(range(1,6)))

array([[1, 2, 3, 4, 5]])

In [150]:
np.asanyarray(np.matrix(range(1,6)))

matrix([[1, 2, 3, 4, 5]])

In [151]:
np.array(range(1,6)).size

5

In [152]:
np.array(range(1,6)).ndim

1

In [153]:
np.array(range(1,6)).dtype

dtype('int64')

In [155]:
np.fromfunction(lambda i,j: i**j, (5,5))

array([[  1.,   0.,   0.,   0.,   0.],
       [  1.,   1.,   1.,   1.,   1.],
       [  1.,   2.,   4.,   8.,  16.],
       [  1.,   3.,   9.,  27.,  81.],
       [  1.,   4.,  16.,  64., 256.]])

In [157]:
np.fromiter(range(1,6),'int')

array([1, 2, 3, 4, 5])

In [158]:
np.array(range(1,6)).shape

(5,)

In [159]:
a = np.array(range(1,6))

In [160]:
b = a 

In [161]:
b[0] = 7

In [162]:
a

array([7, 2, 3, 4, 5])

In [163]:
a[0] = 9

In [164]:
b

array([9, 2, 3, 4, 5])

In [168]:
c = np.copy(a)

In [169]:
c[4] = 0

In [170]:
a

array([9, 2, 3, 4, 5])

In [171]:
c

array([9, 2, 3, 4, 0])