In [183]:
import numpy as np

In [184]:
#Numpy - Array Manipulation.

In [185]:
arr = np.random.rand(2,3)

In [186]:
arr

array([[0.57161913, 0.99827736, 0.23025476],
       [0.3814101 , 0.35088368, 0.95815161]])

In [187]:
arr = np.random.randn(2,3)

In [188]:
arr

array([[-0.23757262,  2.25222441, -0.62454729],
       [-0.45972754, -1.15569605, -0.37197861]])

In [189]:
arr = np.random.randn(3,3)

In [190]:
arr = np.random.randint(1,10 , (4,4))

In [191]:
arr

array([[1, 8, 4, 3],
       [6, 1, 4, 6],
       [3, 1, 7, 1],
       [7, 2, 5, 9]])

In [192]:
arr = np.random.randint(1,5, (3,3))

In [193]:
arr

array([[4, 3, 2],
       [3, 4, 1],
       [4, 4, 2]])

In [194]:
arr.flatten()

array([4, 3, 2, 3, 4, 1, 4, 4, 2])

In [195]:
arr.squeeze()

array([[4, 3, 2],
       [3, 4, 1],
       [4, 4, 2]])

In [196]:
np.reshape(arr,(1,9))

array([[4, 3, 2, 3, 4, 1, 4, 4, 2]])

In [197]:
arr.reshape(1,9)

array([[4, 3, 2, 3, 4, 1, 4, 4, 2]])

In [198]:
arr.reshape(9,1)

array([[4],
       [3],
       [2],
       [3],
       [4],
       [1],
       [4],
       [4],
       [2]])

In [199]:
arr

array([[4, 3, 2],
       [3, 4, 1],
       [4, 4, 2]])

In [200]:
arr.T

array([[4, 3, 4],
       [3, 4, 4],
       [2, 1, 2]])

In [201]:
arr.reshape(1,arr.size)

array([[4, 3, 2, 3, 4, 1, 4, 4, 2]])

In [202]:
arr.flatten()

array([4, 3, 2, 3, 4, 1, 4, 4, 2])

In [203]:
arr.flatten()

array([4, 3, 2, 3, 4, 1, 4, 4, 2])

In [204]:
arr

array([[4, 3, 2],
       [3, 4, 1],
       [4, 4, 2]])

In [205]:
np.expand_dims(arr, axis = 1)

array([[[4, 3, 2]],

       [[3, 4, 1]],

       [[4, 4, 2]]])

In [206]:
np.expand_dims(arr, axis = 1).shape

(3, 1, 3)

In [207]:
np.expand_dims(arr, axis = 0)

array([[[4, 3, 2],
        [3, 4, 1],
        [4, 4, 2]]])

In [208]:
np.expand_dims(arr,axis=0).shape

(1, 3, 3)

In [209]:
np.expand_dims(arr,axis=1)

array([[[4, 3, 2]],

       [[3, 4, 1]],

       [[4, 4, 2]]])

In [210]:
np.expand_dims(arr,axis=0)

array([[[4, 3, 2],
        [3, 4, 1],
        [4, 4, 2]]])

In [211]:
data = np.array([[1],[2],[3]])

In [212]:
data

array([[1],
       [2],
       [3]])

In [213]:
data.flatten()

array([1, 2, 3])

In [214]:
data = np.array([[1] , [2] , [3]])

In [215]:
np.squeeze(data)

array([1, 2, 3])

In [216]:
data.flatten() == np.squeeze(data)

array([ True,  True,  True])

In [217]:
np.squeeze(data)

array([1, 2, 3])

In [218]:
data

array([[1],
       [2],
       [3]])

In [219]:
arr

array([[4, 3, 2],
       [3, 4, 1],
       [4, 4, 2]])

In [220]:
np.repeat(arr,2)

array([4, 4, 3, 3, 2, 2, 3, 3, 4, 4, 1, 1, 4, 4, 4, 4, 2, 2])

In [221]:
np.repeat(data,2)

array([1, 1, 2, 2, 3, 3])

In [222]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [223]:
data

array([[1],
       [2],
       [3]])

In [224]:
np.roll(data,1)

array([[3],
       [1],
       [2]])

In [225]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [226]:
np.roll(data,3)

array([[1],
       [2],
       [3]])

In [227]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [228]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [229]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [230]:
arr

array([[4, 3, 2],
       [3, 4, 1],
       [4, 4, 2]])

In [231]:
data

array([[1],
       [2],
       [3]])

In [232]:
np.diag(np.squeeze(data))

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [63]:
np.diag(data.flatten())

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [233]:
arr.flatten()

array([4, 3, 2, 3, 4, 1, 4, 4, 2])

In [236]:
np.diag(arr.flatten())

array([[4, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 3, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 2]])

In [64]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [65]:
#Numpy - Binary Operators

In [238]:
arr1 = np.random.randint(1,10 , (3,4))
arr2 = np.random.randint(1,10 , (3,4))

In [240]:
print(arr1+arr2)
print(arr1*arr2)
print(arr1-arr2)
print(arr1/arr2)
print(arr1**arr2)
print(~arr1)

[[14 17  7  8]
 [10 14 11 10]
 [14  9  7 11]]
[[48 72 10 15]
 [16 45 28 24]
 [49 18  6 30]]
[[-2  1  3  2]
 [ 6 -4 -3 -2]
 [ 0 -3 -5  1]]
[[0.75       1.125      2.5        1.66666667]
 [4.         0.55555556 0.57142857 0.66666667]
 [1.         0.5        0.16666667 1.2       ]]
[[ 1679616 43046721       25      125]
 [      64  1953125    16384     4096]
 [  823543      729        1     7776]]
[[ -7 -10  -6  -6]
 [ -9  -6  -5  -5]
 [ -8  -4  -2  -7]]


In [243]:
print(np.min(arr1),np.max(arr1),np.mean(arr1),np.median(arr1), np.std(arr1), np.var(arr1), np.sqrt(arr1), np.square(arr1),np.sin(arr1), np.log(arr1),np.exp(arr1),np.arcsin(arr1))

1 9 5.25 5.0 2.0866640042581523 4.354166666666667 [[2.44948974 3.         2.23606798 2.23606798]
 [2.82842712 2.23606798 2.         2.        ]
 [2.64575131 1.73205081 1.         2.44948974]] [[36 81 25 25]
 [64 25 16 16]
 [49  9  1 36]] [[-0.2794155   0.41211849 -0.95892427 -0.95892427]
 [ 0.98935825 -0.95892427 -0.7568025  -0.7568025 ]
 [ 0.6569866   0.14112001  0.84147098 -0.2794155 ]] [[1.79175947 2.19722458 1.60943791 1.60943791]
 [2.07944154 1.60943791 1.38629436 1.38629436]
 [1.94591015 1.09861229 0.         1.79175947]] [[4.03428793e+02 8.10308393e+03 1.48413159e+02 1.48413159e+02]
 [2.98095799e+03 1.48413159e+02 5.45981500e+01 5.45981500e+01]
 [1.09663316e+03 2.00855369e+01 2.71828183e+00 4.03428793e+02]] [[       nan        nan        nan        nan]
 [       nan        nan        nan        nan]
 [       nan        nan 1.57079633        nan]]


/tmp/ipykernel_7088/2997018046.py:1: RuntimeWarning: invalid value encountered in arcsin
  print(np.min(arr1),np.max(arr1),np.mean(arr1),np.median(arr1), np.std(arr1), np.var(arr1), np.sqrt(arr1), np.square(arr1),np.sin(arr1), np.log(arr1),np.exp(arr1),np.arcsin(arr1))


In [67]:
arr1 = np.random.randint(1,10, (2,3))

In [68]:
arr2 = np.random.randint(1,10,(2,3))

In [69]:
arr1

array([[8, 4, 9],
       [4, 1, 2]])

In [70]:
arr2

array([[7, 4, 6],
       [1, 9, 8]])

In [71]:
arr1 + arr2

array([[15,  8, 15],
       [ 5, 10, 10]])

In [72]:
arr1 - arr2

array([[ 1,  0,  3],
       [ 3, -8, -6]])

In [73]:
arr1 * arr2

array([[56, 16, 54],
       [ 4,  9, 16]])

In [74]:
arr1 / arr2

array([[1.14285714, 1.        , 1.5       ],
       [4.        , 0.11111111, 0.25      ]])

In [75]:
arr1+arr2

array([[15,  8, 15],
       [ 5, 10, 10]])

In [76]:
arr1*arr2

array([[56, 16, 54],
       [ 4,  9, 16]])

In [77]:
arr1/arr2

array([[1.14285714, 1.        , 1.5       ],
       [4.        , 0.11111111, 0.25      ]])

In [78]:
arr1-arr2

array([[ 1,  0,  3],
       [ 3, -8, -6]])

In [79]:
arr1**arr2

array([[2097152,     256,  531441],
       [      4,       1,     256]])

In [80]:
arr1**arr2

array([[2097152,     256,  531441],
       [      4,       1,     256]])

In [81]:
arr1

array([[8, 4, 9],
       [4, 1, 2]])

In [82]:
~arr1

array([[ -9,  -5, -10],
       [ -5,  -2,  -3]])

In [83]:
~arr1

array([[ -9,  -5, -10],
       [ -5,  -2,  -3]])

In [84]:
arr1

array([[8, 4, 9],
       [4, 1, 2]])

In [85]:
arr1>arr2

array([[ True, False,  True],
       [ True, False, False]])

In [86]:
arr1 > arr2

array([[ True, False,  True],
       [ True, False, False]])

In [87]:
arr1 < arr2

array([[False, False, False],
       [False,  True,  True]])

In [88]:
#Numpy - String Functions.

In [89]:
arr = np.array(['nikhil' , 'malliykal'])

In [90]:
np.char.lower(arr)

array(['nikhil', 'malliykal'], dtype='<U9')

In [91]:
np.char.title(arr)

array(['Nikhil', 'Malliykal'], dtype='<U9')

In [92]:
np.char.capitalize(arr)

array(['Nikhil', 'Malliykal'], dtype='<U9')

In [93]:
np.char.upper(arr)

array(['NIKHIL', 'MALLIYKAL'], dtype='<U9')

In [94]:
arr

array(['nikhil', 'malliykal'], dtype='<U9')

In [95]:
np.char.upper(arr)

array(['NIKHIL', 'MALLIYKAL'], dtype='<U9')

In [96]:
np.char.capitalize(arr)

array(['Nikhil', 'Malliykal'], dtype='<U9')

In [97]:
np.char.title(arr)

array(['Nikhil', 'Malliykal'], dtype='<U9')

In [98]:
#Numpy - Mathematical Functions.

In [99]:
arr1

array([[8, 4, 9],
       [4, 1, 2]])

In [100]:
np.sin(arr1)

array([[ 0.98935825, -0.7568025 ,  0.41211849],
       [-0.7568025 ,  0.84147098,  0.90929743]])

In [101]:
np.cos(arr1)

array([[-0.14550003, -0.65364362, -0.91113026],
       [-0.65364362,  0.54030231, -0.41614684]])

In [102]:
np.tan(arr1)

array([[-6.79971146,  1.15782128, -0.45231566],
       [ 1.15782128,  1.55740772, -2.18503986]])

In [103]:
np.arcsin(arr1)

/tmp/ipykernel_7088/893717680.py:1: RuntimeWarning: invalid value encountered in arcsin
  np.arcsin(arr1)


array([[       nan,        nan,        nan],
       [       nan, 1.57079633,        nan]])

In [104]:
np.arccos(arr2)

/tmp/ipykernel_7088/2315999628.py:1: RuntimeWarning: invalid value encountered in arccos
  np.arccos(arr2)


array([[nan, nan, nan],
       [ 0., nan, nan]])

In [105]:
np.arctan(arr1+arr2)

array([[1.50422816, 1.44644133, 1.50422816],
       [1.37340077, 1.47112767, 1.47112767]])

In [106]:
np.cos(arr1)

array([[-0.14550003, -0.65364362, -0.91113026],
       [-0.65364362,  0.54030231, -0.41614684]])

In [107]:
np.tan(arr1)

array([[-6.79971146,  1.15782128, -0.45231566],
       [ 1.15782128,  1.55740772, -2.18503986]])

In [108]:
np.exp(arr1)

array([[2.98095799e+03, 5.45981500e+01, 8.10308393e+03],
       [5.45981500e+01, 2.71828183e+00, 7.38905610e+00]])

In [109]:
np.log10(arr1)

array([[0.90308999, 0.60205999, 0.95424251],
       [0.60205999, 0.        , 0.30103   ]])

In [110]:
np.exp(arr1 + arr2)

array([[3.26901737e+06, 2.98095799e+03, 3.26901737e+06],
       [1.48413159e+02, 2.20264658e+04, 2.20264658e+04]])

In [111]:
np.log10(arr1)

array([[0.90308999, 0.60205999, 0.95424251],
       [0.60205999, 0.        , 0.30103   ]])

In [112]:
np.power(arr1, arr2)

array([[2097152,     256,  531441],
       [      4,       1,     256]])

In [113]:
arr1

array([[8, 4, 9],
       [4, 1, 2]])

In [114]:
np.exp(arr1)

array([[2.98095799e+03, 5.45981500e+01, 8.10308393e+03],
       [5.45981500e+01, 2.71828183e+00, 7.38905610e+00]])

In [115]:
np.power(arr1,2)

array([[64, 16, 81],
       [16,  1,  4]])

In [116]:
np.power(arr1, 3)

array([[512,  64, 729],
       [ 64,   1,   8]])

In [117]:
np.mean(arr1)

4.666666666666667

In [118]:
np.median(arr1)

4.0

In [119]:
# np.mode(arr1)

In [120]:
np.var(arr1)

8.555555555555555

In [121]:
np.std(arr1)

2.9249881291307074

In [122]:
np.min(arr1)

1

In [123]:
np.max(arr1)

9

In [124]:
np.mean(arr1)

4.666666666666667

In [125]:
np.median(arr1)

4.0

In [126]:
np.std(arr1)

2.9249881291307074

In [127]:
np.var(arr1)

8.555555555555555

In [128]:
np.min(arr1)

1

In [129]:
np.max(arr1)

9

In [130]:
np.mod(arr1, arr2)

array([[1, 0, 3],
       [0, 1, 2]])

In [131]:
np.add(arr1, arr2)

array([[15,  8, 15],
       [ 5, 10, 10]])

In [132]:
np.subtract(arr1, arr2)

array([[ 1,  0,  3],
       [ 3, -8, -6]])

In [133]:
np.multiply(arr1, arr2)

array([[56, 16, 54],
       [ 4,  9, 16]])

In [134]:
np.divide(arr1, arr2)

array([[1.14285714, 1.        , 1.5       ],
       [4.        , 0.11111111, 0.25      ]])

In [135]:
np.exp(arr1)

array([[2.98095799e+03, 5.45981500e+01, 8.10308393e+03],
       [5.45981500e+01, 2.71828183e+00, 7.38905610e+00]])

In [136]:
#Numpy - Arithmetic Operations.

In [137]:
arr1

array([[8, 4, 9],
       [4, 1, 2]])

In [138]:
arr2

array([[7, 4, 6],
       [1, 9, 8]])

In [139]:
arr1-arr2

array([[ 1,  0,  3],
       [ 3, -8, -6]])

In [140]:
np.subtract(arr1,arr2)

array([[ 1,  0,  3],
       [ 3, -8, -6]])

In [141]:
np.multiply(arr1,arr2)

array([[56, 16, 54],
       [ 4,  9, 16]])

In [142]:
np.mod(arr1,arr2)

array([[1, 0, 3],
       [0, 1, 2]])

In [143]:
np.power(arr1,arr2)

array([[2097152,     256,  531441],
       [      4,       1,     256]])

In [144]:
np.sqrt(arr1)

array([[2.82842712, 2.        , 3.        ],
       [2.        , 1.        , 1.41421356]])

In [145]:
#Numpy - Statistical Functions.

In [146]:
arr1

array([[8, 4, 9],
       [4, 1, 2]])

In [147]:
np.mean(arr1)

4.666666666666667

In [148]:
np.std(arr1)

2.9249881291307074

In [149]:
np.median(arr1)

4.0