In [2]:
import numpy as np

In [3]:
##Sort, Search & Counting Functions.

In [4]:
import numpy as np

In [5]:
arr = np.array([4,2,8,5,3,9,12,56])

In [6]:
arr  = np.random.randint(1,100,(10))

In [7]:
arr

array([84, 87, 50, 87, 25, 68,  7, 74,  9, 80])

In [8]:
arr

array([84, 87, 50, 87, 25, 68,  7, 74,  9, 80])

In [9]:
np.sort(arr)

array([ 7,  9, 25, 50, 68, 74, 80, 84, 87, 87])

In [10]:
np.sort(arr)

array([ 7,  9, 25, 50, 68, 74, 80, 84, 87, 87])

In [11]:
np.searchsorted(arr,87)

10

In [34]:
arr = np.random.randint(1,11,10)
print(arr)
print(np.where(arr==2))
np.searchsorted(arr,2)

[ 7  8 10  5  5  1  3  1  4  3]
(array([], dtype=int64),)


8

In [30]:
np.searchsorted(arr,6)

2

In [13]:
arr1 = np.array([0,324,645,65,6,6,0,0,0,234])

In [13]:
np.count_nonzero(arr1)

6

In [17]:
np.count_nonzero(arr1)

6

In [18]:
np.where(arr1>0)

(array([1, 2, 3, 4, 5, 9]),)

In [14]:
np.where(arr1 > 0 )

(array([1, 2, 3, 4, 5, 9]),)

In [21]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [23]:
np.where(arr1>10)

(array([1, 2, 3, 9]),)

In [22]:
np.extract(arr1>10, arr1)

array([324, 645,  65, 234])

In [18]:
np.extract(arr1 >2,arr1)

array([324, 645,  65,   6,   6, 234])

In [25]:
arr

array([86, 72, 68, 27, 59, 78, 43, 70, 83, 48])

In [26]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [24]:
np.extract(arr>0, arr1)

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [27]:
np.extract(arr1>0, arr1)

array([324, 645,  65,   6,   6, 234])

In [19]:
#Numpy - Byte Swapping.

In [28]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [24]:
arr.byteswap(True)

array([ 288230376151711744,  144115188075855872,  576460752303423488,
        360287970189639680,  216172782113783808,  648518346341351424,
        864691128455135232, 4035225266123964416])

In [29]:
arr

array([86, 72, 68, 27, 59, 78, 43, 70, 83, 48])

In [30]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [31]:
arr.byteswap(True)

array([6196953087261802496, 5188146770730811392, 4899916394579099648,
       1945555039024054272, 4251398048237748224, 5620492334958379008,
       3098476543630901248, 5044031582654955520, 5980780305148018688,
       3458764513820540928])

In [32]:
arr

array([6196953087261802496, 5188146770730811392, 4899916394579099648,
       1945555039024054272, 4251398048237748224, 5620492334958379008,
       3098476543630901248, 5044031582654955520, 5980780305148018688,
       3458764513820540928])

In [28]:
#Numpy - Copies &Views.

In [33]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [34]:
a = np.copy(arr1)

In [35]:
a

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [31]:
a = np.copy(arr1)

In [37]:
b = arr1.view()

In [38]:
a

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [40]:
b

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [41]:
b = arr1.view()

In [42]:
b = arr1

In [43]:
b

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [44]:
b[0] = 234

In [45]:
b

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [46]:
arr1

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [48]:
a = np.copy(arr1)

In [49]:
a

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [50]:
arr1

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [51]:
a[0] = 143

In [52]:
a

array([143, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [54]:
arr1

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [55]:
b = arr1.view()

In [56]:
arr1[1] = 423

In [57]:
arr1

array([234, 423, 645,  65,   6,   6,   0,   0,   0, 234])

In [58]:
b

array([234, 423, 645,  65,   6,   6,   0,   0,   0, 234])

In [60]:
 b[2] = 546

In [61]:
arr1

array([234, 423, 546,  65,   6,   6,   0,   0,   0, 234])

In [62]:
a

array([143, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [63]:
c = arr1

In [64]:
arr1[3] = 56

In [66]:
c

array([234, 423, 546,  56,   6,   6,   0,   0,   0, 234])

In [67]:
arr1

array([234, 423, 546,  56,   6,   6,   0,   0,   0, 234])

In [3]:
import numpy as np

In [16]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [69]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [72]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
import numpy.matlib as nm

In [20]:
nm.zeros(3)

matrix([[0., 0., 0.]])

In [75]:
nm.ones(3)

matrix([[1., 1., 1.]])

In [76]:
nm.eye(3)

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [65]:
#Numpy - Matrix Library.

In [41]:
import numpy.matlib as nm

In [22]:
nm.zeros((2,5))

matrix([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [43]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [44]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [45]:
#Numpy - Linear Algebra

In [48]:
arr1 = np.random.randint([[2,3] , [4,5]])

In [49]:
arr2 = np.random.randint([[5,3] , [2,5]])


In [50]:
arr1

array([[0, 1],
       [1, 4]])

In [51]:
arr2

array([[2, 2],
       [1, 2]])

In [52]:
np.dot(arr1,arr2)

array([[ 1,  2],
       [ 6, 10]])

In [53]:
arr1@arr2

array([[ 1,  2],
       [ 6, 10]])

In [77]:
arr1 = np.random.randint(1,10,(3,3))

In [78]:
arr2 = np.random.randint(1,10,(3,3))

In [80]:
arr1 + arr2

array([[13,  4, 16],
       [ 3, 10, 10],
       [14,  5,  5]])

In [81]:
arr1 * arr2

array([[40,  4, 63],
       [ 2, 24, 24],
       [45,  6,  4]])

In [82]:
arr1 @ arr2

array([[87, 49, 52],
       [50, 46, 36],
       [94, 42, 75]])

In [83]:
np.dot(arr1, arr2)

array([[87, 49, 52],
       [50, 46, 36],
       [94, 42, 75]])

In [84]:
arr1 @ arr2

array([[87, 49, 52],
       [50, 46, 36],
       [94, 42, 75]])